### ISSUE TITLE
Hash method called on undefined value on line 434 of SafeBrowsing4.pm

### ISSUE THREAD

**Issue by djugessur** [juliensobrier/Net-Google-SafeBrowsing4#10]
Hi,

While doing more tests, I have run into issues where the hash function is being called on undefined values on line 434 of SafeBrowsing4.pm.  I have attached a patch for this

[URI.patch.txt](https://github.com/juliensobrier/Net-Google-SafeBrowsing4/files/1277694/URI.patch.txt)

Thanks

Deepu

**Comment by djugessur** [comment]
I noticed another issue with this.  If you run with the following 2 links:

http://jakuboweb.com/message.html
http://www.yac.mx?source=3Demail

The first one is not caught despite being in the safe browsing db.

Here is a patch to address this:

[URI.patch2.txt](https://github.com/juliensobrier/Net-Google-SafeBrowsing4/files/1284907/URI.patch2.txt)

The real fix however would involve a modification of the regex to handle the second link, as browsers tend to insert the "/" char before the "?".

Thanks

Deepu

**Comment by geever** [comment]
Applied your first patch. About the second: It actually revealed a normalizing bug a slash should have been added between the domain and the query. I'll look into that.

**Comment by geever** [comment]
Fixed the normalization and updated the splitting logic as well. I hope it is all good now. Thanks for reporting!
