### ISSUE TITLE
Full hash request limitation is set to 500 by Google

### ISSUE THREAD

**Issue by papaiatis** [juliensobrier/Net-Google-SafeBrowsing4#15]
According to my logs it looks like Google refuses the `bulk` full hash requests for more than 500 entries.

I'd like to request a feature that automatically splits the list of full hash requests by chunks of 500 entries and sends multiple requests after each other and eventually combines the results into one and returning back to the calling client. 

Thank you!

**Comment by juliensobrier** [comment]
commit e4ced7140cce85f650ead4f6c653fe610f6955d8
