### ISSUE TITLE
Errors in parsing URLs

### ISSUE THREAD

**Issue by juliensobrier** [juliensobrier/Net-Google-SafeBrowsing4#18]
URL 37: http://www.google.com%22?format=%22json
Use of uninitialized value $host in pattern match (m//) at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 102.
Use of uninitialized value $host in split at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 103.
Use of uninitialized value $path_query in split at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 115.
Use of uninitialized value $path_query in pattern match (m//) at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 123.
Use of uninitialized value $scheme in concatenation (.) or string at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 131.
Use of uninitialized value $domain in concatenation (.) or string at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 131.
Use of uninitialized value $path in concatenation (.) or string at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 131.
Can't call method "hash" on an undefined value at /usr/local/share/perl5/Net/Google/SafeBrowsing4.pm line 434.

URL 65: http://www.solmelia.com?dasdasd=dsasdasd&sdaasd=dasd
Use of uninitialized value $host in pattern match (m//) at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 102.
Use of uninitialized value $host in split at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 103.
Use of uninitialized value $path_query in split at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 115.
Use of uninitialized value $path_query in pattern match (m//) at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 123.
Use of uninitialized value $scheme in concatenation (.) or string at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 131.
Use of uninitialized value $domain in concatenation (.) or string at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 131.
Use of uninitialized value $path in concatenation (.) or string at /usr/local/share/perl5/Net/Google/SafeBrowsing4/URI.pm line 131.
Can't call method "hash" on an undefined value at /usr/local/share/perl5/Net/Google/SafeBrowsing4.pm line 434.

**Comment by geever** [comment]
I cannot reproduce these errors, it must be Perl/URI.pm dependent. (My setup is Debian9, Perl 5.24.1, URI 1.71 (but tested with 1.73 also), latest gsb4. On what environment you get these errors?

**Comment by juliensobrier** [comment]
CPAN didn't have the last release. I'll close it after I verify it with the new CPAN version.

**Comment by juliensobrier** [comment]
No issue with the latest CPAN release.
