### ISSUE TITLE
Is it normal to have `last_udpate` key in updates.gdb4?

### ISSUE THREAD

**Issue by ldidry** [juliensobrier/Net-Google-SafeBrowsing4#19]
Hello,

I'm looking to create a DB storage for Net::Google::SafeBrowsing4 for my [application](https://framagit.org/luc/lstu) and I'm looking into the created files. 

I saw that `updates.gdb4` contains `last_udpate` and `last_update` keys:
```
$VAR1 = {
          'errors' => 0,
          'last_update' => 0,
          'next_update' => '1536514777.53106',
          'last_udpate' => '1536512923.22054'
        };
```

Is it normal? Is it harmless? Seems like a typo to me, but I don't know what are the consequences, if any.

**Comment by juliensobrier** [comment]
There's a type, I'll look into it. Thanks for reporting it.
