### ISSUE TITLE
Crash when gsb->update() is called the first time

### ISSUE THREAD

**Issue by llkhacquan** [juliensobrier/Net-Google-SafeBrowsing4#23]
I meet this bug when gsb->update() is called the first time. (storage is empty).
```
2019/03/05 20:30:01 Load /etc/coccoc-gsb4/data/updates.gdb4 (reset)
2019/03/05 20:30:01 time for update: 0 / 1551792601.67377
Can't use an undefined value as an ARRAY reference at /usr/local/share/perl/5.26.1/Net/Google/SafeBrowsing4.pm line 693.
```
Hope this helps.

**Comment by geever** [comment]
@llkhacquan Could you show us your script, and/or a more detailed reproduction plan, and version of your GSB module. Line 693 should only die on empty lists which should not happen :)

**Comment by llkhacquan** [comment]
I used the latest gsb4 version from cpan `sudo cpan intall Net::Google::SafeBrowsing4`
Note that this crash does not always happen. The script is very simple [here](https://gist.github.com/llkhacquan/b9265d2ac61e64ea83c7fbbf9407b917).
After few debuggings, I think the reason can be:
- initial `storage` is empty.
- `get_lists` gets error (403 in my case, even when my api is correct).
![Screenshot from 2019-03-09 13-45-03](https://user-images.githubusercontent.com/3724362/54067415-5ae25c80-4272-11e9-80c0-78dba049ab35.png)

**Comment by geever** [comment]
Thanks for the clarification, I managed to reproduce the issue.
4e4019feb4e471622d7544907a6a90c10a6bc92c addresses that issue, update will return with SERVER_ERROR if $all_lists is undef.
