### ISSUE TITLE
Can't use an undefined value as an ARRAY reference at /usr/local/share/perl/5.14.2/Net/Google/SafeBrowsing4.pm line 615

### ISSUE THREAD

**Issue by 07Sai0** [juliensobrier/Net-Google-SafeBrowsing4#26]
Still getting following error 

Can't use an undefined value as an ARRAY reference at /usr/local/share/perl/5.14.2/Net/Google/SafeBrowsing4.pm line 615

**Comment by geever** [comment]
Could you please share a code snippet that you get it with?
We can definitely improve the error handing around the mentioned code line, but from a first glance I suspect the root cause be elsewhere, like: missing/not valid api key, not properly configured client.
Thank You!

**Comment by geever** [comment]
Fixed the case that could reset the list, causing this issue. As I mentioned before, it could only happen if downloading the available lists failed.
