### ISSUE TITLE
Better error handling needed when requesting full hashes fails

### ISSUE THREAD

**Issue by papaiatis** [juliensobrier/Net-Google-SafeBrowsing4#7]
When I call `$gsb->lookup(...)` sometimes I see this message in the logs: `Full hash request failed` but my client software keeps working because the `lookup` method returns an empty array back, thus I don't really have the chance to catch this error.

I would expect this method to either throw an exception or return back an error flag in cases of this.

**Comment by juliensobrier** [comment]
last_error is now updated when the full hash request fails
