### ISSUE TITLE
Using binary search in get_prefixes

### ISSUE THREAD

**Issue by djugessur** [juliensobrier/Net-Google-SafeBrowsing4#8]
Hi, 

I've been playing around with Net-Google-SafeBrowsing4 and loving it.  Thank you for this awesome effort.  Since I'm planning on using it with emails, I ran into speed issues when querying with lots of links. 
 
Consequently I found that implementing binary search when calling get_prefixes greatly increased search speeds.  Please have a look at the patch.  MlogN vs MN where M is number of hashed links to search for and N is the number of hashed links in the DB.  

The patch is for Storage\File.pm.

[File.pm.patch.txt](https://github.com/juliensobrier/Net-Google-SafeBrowsing4/files/1194811/File.pm.patch.txt)

**Comment by juliensobrier** [comment]
Thank you, I have merged your patch
