### ISSUE TITLE
Potential bug when looking up full hashes

### ISSUE THREAD

**Issue by djugessur** [juliensobrier/Net-Google-SafeBrowsing4#9]
Hi,

Line 556 of SafeBrowsing4.pm states:

if (scalar(keys(%$lookup_hashes)) == 0) {
  return @results;
}

Shouldn't this be something like:

if ($found == scalar(@prefixes)) {
  return @results;
}

I don't understand the logic of counting the keys of the lookup_hashes.  

For example, if I lookup prefixes for 21 hashes, find 1 prefix in the local database, then find 1 full hash, only one is deleted from the full hash.  Consequently you will query Google for the prefix that already had a full hash found cached locally before the expired time.  

Here is a log for this behaviour:

2017/08/25 11:04:51 DEBUG Looking up prefixes for 21 hashes 
2017/08/25 11:04:51 DEBUG Number of lists: 8 
2017/08/25 11:04:51 DEBUG Local lookup: 0.00211620330810547s  
2017/08/25 11:04:51 DEBUG Found 1 prefix(s) in local database 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Number of full hashes on file: 862 
2017/08/25 11:04:51 DEBUG Full hashes found locally: 1 
2017/08/25 11:04:51 DEBUG Stored hashes lookup: 0.0446920394897461s  
2017/08/25 11:04:51 DEBUG Looking up 20 hashes

I noticed this bug as I hit the 10k lookup limit while doing a load test with the same URL.  Despite the link existing in the local full hash cash, queries kept happening.

As a consequence of my fix, I also had to update get_full_hashes in File.pm with:

$self->{data}->{ $self->{files}->{full_hashes} } = $db;

After retrieving the full hash as add_full_hashes is not called as often.

I've included the 2 patches.

[SafeBrowsing4.patch.txt](https://github.com/juliensobrier/Net-Google-SafeBrowsing4/files/1252292/SafeBrowsing4.patch.txt)
[File.patch.txt](https://github.com/juliensobrier/Net-Google-SafeBrowsing4/files/1252298/File.patch.txt)

Thanks

Deepu

**Comment by geever** [comment]
Be careful: A full hash may be $found in more than one list and it is not the same as the number of prefixes we are to look up.

I think what you would like to have is a hierarchy of URIs so if the top level domain is reported to be dangerous the "leaf" URIs are not looked up, don't you? 
Note that the lookup() function is to support more (different) URIs in a single call (to reduce number of GSB lookups).

**Comment by djugessur** [comment]
I ran into this issue when I would have a list of say 10 urls, with one of them being in the local DB (i.e. a match).  If I send this list in a loop, with the old logic, the one match would keeping hitting the google server despite being in the full cache as scalar(keys(%$lookup_hashes) would never be 0.

**Comment by geever** [comment]
In 5815efb I tied all hashes to the originating URI and dropped every hash from remote lookup that was generated from a URI that was found locally or which URIs' parents were found locally. I believe this will solve your problem. However this was a BIG change and have no unittests yet, please test it extensively!

**Comment by djugessur** [comment]
So far it looks good.  Thanks geever.  Need to test more in a prod environment.
